### ISSUE TITLE
MuPDFWrapper DLL Missing

### ISSUE THREAD

**Issue by Checkman44** [arklumpus/VectSharp#2] opened 2020-11-23 11:43 UTC
SaveAsPNG throws System.DllNotFoundException: 'Unable to load DLL 'MuPDFWrapper' on Windows

have you run into this problem? 

I have tried to build this dll with ninja and cmake according to MuPdf tutorial but build failed.

Any response would be greatly appreciated. Thank you.

**Comment by arklumpus** [comment] 2020-11-23 12:54
Hi, you should not need to build the MuPDFWrapper dll, because that is included in the MuPDFCore NuGet package (which should be installed automatically when you install VectSharp.Raster).

I tried replicating this by creating a new project and installing the VectSharp and VectSharp.Raster NuGet packages, but everything seems to work as expected.

Can you provide some more information?

1. What NuGet packages (and which versions) did you install? You should have VectSharp 1.6.0 and VectSharp.Raster 2.0.3.
2. How are you compiling the solution? (e.g. Just F5/debug in Visual Studio?)

I would also suggest:

1. Install the MuPDFCore package in your project.
2. Create a new project in your solution, install VectSharp and VectSharp.Raster, and see if you can create a simple PNG.
3. Create a new solution and a new project, install VectSharp and VectSharp.Raster, and see if you can create a simple PNG.

Let me know if any of these works!

**Comment by Checkman44** [comment] 2020-11-23 13:08
1.1 I installed latest packages, 1.6.0. VectSharp, 2.0.3. and VectSharp.Raster +VectSharp.SVG 1.2.2 which works great for SVG
1.2 I am just running a console app with F5 in Visual Studio.

One thing that might be important - my console app is .NET Framework 4.6.1. which I cannot change due to server specs.

I will try suggested steps and let you know.

Thank you for your swift reply!

**Comment by arklumpus** [comment] 2020-11-23 13:15
OK, I may have been able to identify the issue. I was assuming that you were using .NET core. The problem seems to be that for some reason, the DLL is not copied when you compile for .NET framework. I am looking into it, but in the meantime what you can do is:

1. Create a new .NET Core solution, install VectSharp and VectSharp.Raster, and use it to create a simple PNG (anything will do, you just need this to compile).
2. Go into the Debug folder, you should have a subfolder called `runtimes` which in turn contains three folders (`linux-x64`, `osx-64` and `win-x64`). Go into `win-x64` and in the `native` folder contained therein. Here you should find MuPDFWrapper.dll.
3. Just copy this file in the same folder as your .NET framework executable

**Comment by Checkman44** [comment] 2020-11-23 13:59
I have created .NET core console app and tested PNG rendering and it worked. 

Copied the MuPDFWrapper.dll in bin/Debug which did not work. I even tried multiple hierarchies from .NET core project if it searches another path and it did not work either.

**Comment by arklumpus** [comment] 2020-11-23 14:13
That is surprising... Here is what I did (and worked):

1. Create a new .NET 4.6.1 console app
2. Install VectSharp and VectSharp.Raster. Write code to create a simple PNG.
3, Change target platform to x64 (in the project properties)
4. Compile and run the program. It throws DLLNotFoundException.
5. Copy the MuPDFWrapper.dll in the same folder as the executable.
6. Run again the program, now it works.

Are you copying the file in the _executable_ folder? For example, if your solution contains a class library project that uses VectShap.Raster and a console executable project that references the class library, you need to copy the DLL in the console executable project's debug folder.

**Comment by Checkman44** [comment] 2020-11-23 14:20
You are right. I copied it into the Debug folder, while it was building in x64 folder. Now it works! Thanks a lot. You saved me big time.

**Comment by arklumpus** [comment] 2020-11-23 14:21
Perfect! Glad to know it worked. I will leave this open until I manage to fix the NuGet package.

**Comment by arklumpus** [comment] 2020-12-31 03:50
Unfortunately I could not find a reasonable way to fix the NuGet package. Aside from issues with the NuGet itself (when used in SDK-style projects vs non-SDK-style projects), the problem is that with a .NET Framework target you do not really know which platform the program will be running on at compile time - e.g. you could be running the same executable directly on Windows or on Linux using `mono` etc.

A workaround would be to copy the three library files for Windows, macOS and Linux to the output folder on every platform, but that would add ~75MB of unnecessary files, which I think would be unacceptable. The other solution is to manually copy the only the needed file, and I think this is the most reasonable option here.

Accordingly, I have updated the readmes for VectSharp and MuPDFCore with instructions to do this, and I am closing the issue. Ideally, as systems get updated and people start using the new .NET this problem should not occur.

**Closed by arklumpus** 2020-12-31 03:50 UTC
