### ISSUE TITLE
Page object, when a RasterImage is drawn outside of the Page bounds, throws the exception "Cannot draw image because the source image does not overlap the target image" when calling SaveAsImage

### ISSUE THREAD

**Issue by ArtificialRaccoon** [arklumpus/VectSharp#33] opened 2022-06-01 14:36 UTC
Library versions in use:
VectSharp 2.3.0
VectSharp.Raster.ImageSharp 1.1.2-beta14
VectSharp.ImageSharpUtils 1.0.1-beta14
SixLabors.ImageSharp 2.1.2
SixLabors.ImageSharp.Drawing 1.0.0-beta14

When I attempt to draw a RasterImage at a given point, if any of the RasterImage extents end up falling outside of the Page dimensions, an exception is thrown when calling "SaveAsImage" from the Page object.   If I draw any other elements (Rectangles, paths, etc), they are neatly clipped from the final image; no exception is thrown.  I am currently rendering MapBox Vector Tiles, and some raster data is intended to be partially drawn outside the bounds of the tile, making this exception problematic.  I have tried using ClippingPath to potentially skirt the exception, but it appears to not solve the issue.  I could manually clip the raster data, but I'd rather not if I could avoid it.

The specific exception is:
SixLabors.ImageSharp.ImageProcessingException: 'Cannot drawn image because the source image does not overlap the target image'

It appears you referenced something similar to this in #25?

**Comment by arklumpus** [comment] 2022-06-01 18:46
Hi! Yeah, this seems similar to what was happening in previous versions of ImageSharp. I think this is a bug in ImageSharp and I have reported it to them (SixLabors/ImageSharp.Drawing#226), though there is a possibility that this might be intended behaviour.

I can implement a fix for this in VectSharp.Raster.ImageSharp, but as I mentioned in #32 I need to wait until I get official permission to contribute to open-source projects before releasing it 🤦‍♂️

**Comment by GuidedByCthulhu** [comment] 2022-06-01 20:25
Ah, I didn't see that!  My apologies for raising a potentially duplicate issue.

**Comment by JimBobSquarePants** [comment] 2022-06-02 14:19
I think it's something we should definitely have a look at for V3 though, it should be a simple case of using only the intersection of the two rectangles.

**Closed** 2022-06-14 16:18 UTC

**Comment by arklumpus** [comment] 2022-06-14 16:28
This should be fixed in [VectSharp.Raster.ImageSharp 1.1.3-beta14.16](https://www.nuget.org/packages/VectSharp.Raster.ImageSharp/1.1.3-beta14.16)!
